# Algorithm extensions for MassGen
# Based on the original MassGen framework: https://github.com/Leezekun/MassGen
# Extensions and modifications for pluggable algorithms by Basit Mustafa (@24601)
"""
Base algorithm interface for orchestration algorithms.

This module defines the abstract base class that all orchestration algorithms
must implement, providing a consistent interface for agent coordination.
"""

import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, Optional

from ..types import AgentState, SystemState, TaskInput


@dataclass
class AlgorithmResult:
    """Result from running an orchestration algorithm.

    Attributes:
        answer: The final answer generated by the algorithm
        consensus_reached: Whether consensus was reached among agents
        representative_agent_id: ID of the agent selected to present the answer
        session_duration: Total duration of the session in seconds
        summary: Summary statistics about the run
        system_logs: Detailed system logs for analysis
        algorithm_specific_data: Any algorithm-specific data to include
    """

    answer: str
    consensus_reached: bool
    representative_agent_id: Optional[int]
    session_duration: float
    summary: Dict[str, Any]
    system_logs: Dict[str, Any] = field(default_factory=dict)
    algorithm_specific_data: Dict[str, Any] = field(default_factory=dict)


class BaseAlgorithm(ABC):
    """Abstract base class for orchestration algorithms.

    All orchestration algorithms must inherit from this class and implement
    the required methods. This ensures a consistent interface across different
    algorithm implementations.
    """

    def __init__(
        self,
        agents: Dict[int, Any],
        agent_states: Dict[int, AgentState],
        system_state: SystemState,
        config: Dict[str, Any],
        log_manager: Optional[Any] = None,
        streaming_orchestrator: Optional[Any] = None,
    ) -> None:
        """Initialize the algorithm with shared orchestrator state.

        Args:
            agents: Dictionary mapping agent IDs to agent instances
            agent_states: Dictionary mapping agent IDs to their states
            system_state: Shared system state
            config: Algorithm-specific configuration
            log_manager: Optional log manager for tracking events
            streaming_orchestrator: Optional streaming display orchestrator
        """
        self.agents = agents
        self.agent_states = agent_states
        self.system_state = system_state
        self.config = config
        self.log_manager = log_manager
        self.streaming_orchestrator = streaming_orchestrator

    @abstractmethod
    def run(self, task: TaskInput) -> AlgorithmResult:
        """Run the orchestration algorithm on a task.

        This is the main entry point for the algorithm. It should coordinate
        the agents to work on the task and return the final result.

        Args:
            task: The task to be solved by the agents

        Returns:
            AlgorithmResult containing the final answer and metadata
        """

    @abstractmethod
    def get_algorithm_name(self) -> str:
        """Get the name of the algorithm.

        Returns:
            A string identifier for the algorithm
        """

    @abstractmethod
    def validate_config(self) -> bool:
        """Validate the algorithm configuration.

        Returns:
            True if configuration is valid, raises exception otherwise
        """

    def update_agent_answer(self, agent_id: int, answer: str) -> None:
        """Update an agent's answer.

        Default implementation that can be overridden by specific algorithms.

        Args:
            agent_id: ID of the agent updating their answer
            answer: New answer content
        """
        if agent_id not in self.agent_states:
            raise ValueError(f"Agent {agent_id} not registered")

        self.agent_states[agent_id].add_update(answer)

        # Log the update
        if self.log_manager:
            self.log_manager.log_agent_answer_update(
                agent_id=agent_id,
                answer=answer,
                phase=self.system_state.phase,
                orchestrator=self,
            )

    def mark_agent_failed(self, agent_id: int, reason: str = "") -> None:
        """Mark an agent as failed.

        Default implementation that can be overridden by specific algorithms.

        Args:
            agent_id: ID of the agent to mark as failed
            reason: Optional reason for the failure
        """
        if agent_id not in self.agent_states:
            raise ValueError(f"Agent {agent_id} not registered")

        old_status = self.agent_states[agent_id].status
        self.agent_states[agent_id].status = "failed"
        self.agent_states[agent_id].execution_end_time = time.time()

        # Update streaming display
        if self.streaming_orchestrator:
            self.streaming_orchestrator.update_agent_status(agent_id, "failed")
            failure_msg = f"💥 Agent {agent_id} failed: {reason}" if reason else f"💥 Agent {agent_id} failed"
            self.streaming_orchestrator.add_system_message(failure_msg)

        # Log the failure
        if self.log_manager:
            self.log_manager.log_agent_status_change(
                agent_id=agent_id,
                old_status=old_status,
                new_status="failed",
                phase=self.system_state.phase,
            )

    def cleanup(self) -> None:
        """Clean up any resources used by the algorithm.

        Default implementation does nothing, but can be overridden.
        """
